channels:
- conda-forge
dependencies:
- ipykernel
- myst-parser
- nbsphinx
- sphinx-gallery
- sphinx-rtd-theme
- versioneer
- h5py =3.12.1
- neo4j-python-driver-rust-ext =5.25.0.0
- numpy =2.2.2
- psycopg2 =2.9.9
- pyiron_workflow =0.12.0
- sqlalchemy =2.0.38
