# This workflow will install Python dependencies, run integration tests and lint with a variety of Python versions
# The idea of this workflow is to run more expensive tests only for a push to master or if a specific
# `integration` label is set on a pull request.

name: Integration tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [labeled, opened, synchronize, reopened]

jobs:
  build:
    if: |
      github.event_name == 'push' ||
      ( github.event_name == 'pull_request'  && contains(github.event.pull_request.labels.*.name, 'integration' ))
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.9
        mamba-version: "0.17.0"
        channels: conda-forge
        channel-priority: strict
        auto-update-conda: true  
        environment-file: .ci_support/environment.yml
    - name: Setup
      shell: bash -l {0}
      run: |
        python .ci_support/pyironconfig.py
        pip install --no-deps .
    - name: Test
      shell: bash -l {0}
      run: coverage run --omit pyiron/_version.py -m unittest discover test_integration
