name: PostgreSQL
on: push

jobs:
  # Label of the container job
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    container: ubuntu:latest

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_USER: pyiron
          POSTGRES_PASSWORD: pyiron
          POSTGRES_DB: pyiron_workflow
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: '3.12'
          channels: conda-forge
          environment-file: .ci_support/environment.yml

      - name: Install dependencies
        shell: bash -el {0}
        run: pip install neo4j-rust-ext

      - name: Run tests
        shell: bash -el {0}
        run: python -m unittest discover -v
